name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
    steps:
#      - name: Use Node.js
#        uses: actions/setup-node@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip setuptools
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101 .  # B101 is assert statements
      - run: black --check . || true
      - run: codespell --quiet-level=2 --skip=./exmples/*  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: isort --check-only --profile black --skip examples . || true
      - run: pip install -r requirements.txt || true
      - run: pip install python-tds Sqlalchemy
      - run: mypy --ignore-missing-imports --exclude=examples/* . || true
#      - run: pytest || true
#      - run: pytest --doctest-modules || true
#      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
#      - run: safety check
